site_name: Hydralette Docs
site_url: https://valeknappich.github.io/hydralette/
repo_url: https://github.com/valeknappich/hydralette

theme:
  # name: readthedocs
  name: material
  features:
    - navigation.sections
    - navigation.tracking
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      # primary: teal
      # accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      # primary: teal
      # accent: lime

nav:
  - Home: index.md
  - Examples: examples.md
  - API: API.md

plugins:
  - search
  # - social
  - mkdocstrings


markdown_extensions:
  - admonition
  - pymdownx.extra
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/valeknappich/hydralette

copyright: |
  &copy; 2023 <a href="https://github.com/ValeKnappich"  target="_blank" rel="noopener">Valentin Knappich</a>